name: PR140686 (ld64)

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./run.sh /Applications/Xcode_16.3.app/Contents/Developer
        working-directory: ./140686/rust/origin
