name: PR140686 (ld64)

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-16-2:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./run.sh /Applications/Xcode_16.2.app/Contents/Developer
        working-directory: ./140686/rust/origin
  rust-15-2:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./run.sh /Applications/Xcode_15.2.app/Contents/Developer
        working-directory: ./140686/rust/origin
  rust-15-2-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./run.sh /Applications/Xcode_15.2.app/Contents/Developer
        working-directory: ./140686/rust/origin
