name: PR141306

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ring-xcode15-2:
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./ring.sh /Applications/Xcode_15.2.app/Contents/Developer
        working-directory: ./141306
  ring-xcode15-3:
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./ring.sh /Applications/Xcode_15.3.app/Contents/Developer
        working-directory: ./141306
  minimum-xcode15-2:
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./minimum.sh /Applications/Xcode_15.2.app/Contents/Developer
        working-directory: ./141306
  minimum-xcode15-3:
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./minimum.sh /Applications/Xcode_15.3.app/Contents/Developer
        working-directory: ./141306
